[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "prochem"
version = "1.0.0"
authors = [
  { name = "Alexander Solovykh", email = "solovykh.aa19@physics.msu.ru" },
]
description = "ProChem is a library and application for reading, analyzing and visualizing atomistic simulation results."
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.23.5",
    "pandas>=2.0.3",
]

[project.scripts]
prochem = "prochem.adapters.qt.app:main"

[project.optional-dependencies]
qt = [
    "numba>=0.61.0",
    "pillow>=11.2.1",
    "matplotlib>=3.10.1",
    "PyOpenGL>=3.1.8",
    "PySide6>=6.9.2",
]
jupyter = [
    "ipywidgets>=8.1",
    "plotly>=6.0",
]
web = [
    "fastapi>=0.115",
    "pydantic>=2.0",
    "uvicorn>=0.34",
]
dev = [
    "pytest>=8.0",
    "ruff>=0.11",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"prochem.adapters.qt.generated" = ["style_sheets/*.css"]
"prochem.adapters.qt.opengl.shaders" = ["*.glsl"]
